# version: '3'
# services:
#   app:
#     container_name: docker-node-mysql
#     restart: always
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     ports: 
#       - '1337:1337'
#   #   # environment:
#   #   #   DATABASE_HOST: mysql
#   #     # DATABASE_USER_NAME: root
#   #     # DATABASE_PASSWORD: root
#   mysql: 
#     container_name: mysql
#     image: mysql
#     ports:
#       - '3306'
#     environment:
#       MYSQL_DATABASE: sailslogin
#       MYSQL_USER: root
#       MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

#       # - MYSQL_ROOT_PASSWORD=sails


version: "3"
services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3300:3306
    command: --default-authentication-plugin=mysql_native_password
    # env_file: 
    #   .env
    environment: 
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test2
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    ports:
      - "1337:1337"